### ISSUE TITLE
Documentation Proposal [WIP]

### ISSUE THREAD

**Issue by Ninir** [CentralReport/CentralReport#23]
### CentralReport (entry point)
- What is CR?
- What is it designed for?
- Check the site
### Getting Started With CentralReport
- Prerequisites
- Installation
- Next Steps (links to other parts)

---
- [x] Install CR
- [x] Uninstall CR
- [ ] UI to check your devices
- [ ] Logging
- [ ] Hooks?
- [ ] Contributing

This will be updated as soon as we have ideas to complete it.

**Comment by Guimove** [comment]
Install / Uninstall OK https://github.com/miniche/CentralReport/wiki/Installation

**Comment by Ninir** [comment]
@Guimove FOr sure, the goal of this PR is to have a real doc, with a hierarchical approach

**Comment by miniche** [comment]
I've written basic documentation for launching the alpha version : https://github.com/miniche/CentralReport/wiki

Documentation will be improved continuously.

**Comment by miniche** [comment]
Anyone have already used a wiki to write documentation (like dokuwiki or other)?
Do you have some ideas to build a beautiful doc?

**Comment by Ninir** [comment]
A wiki is fine. However, we can also use github pages :)

**Comment by miniche** [comment]
All right, but Github wiki is limited (no search function, no internationalization, etc.).
For the moment, we will use the Github wiki, it's more practical than installing our own wiki. But I think that we will talk about build a custom documentation when CR Online will be in beta.

**Comment by Ninir** [comment]
Alright\* :)

We could have a wiki yep... but it means we should have a lot of doc to provide, which is not the case atm.

**Comment by miniche** [comment]
(For "all right", I think that two spelling are good: http://english.stackexchange.com/questions/12996/is-it-alright-or-allright)

CentralReport structure changes quickly: fixes, updates, improvements... Write a documentation is very difficult for the moment, we should edit it every day.

**Comment by miniche** [comment]
The official documentation of the project is hosted at http://docs.centralreport.net.
It will be updated soon with new events related to the project and CentralReport Online :)
