### ISSUE TITLE
Choosing the CentralReport license

### ISSUE THREAD

**Issue by miniche** [CentralReport/CentralReport#24]
Many licenses are available, and we must choose one of them for CentralReport.

CentralReport for Unix/Linux must be Open Source. Everyone should be able to fork the projet, change code for its own needs, contribute on the main project, etc.

Some licenses we can use : 
- Apache 2.0
- BSD
- MIT
- GNU GPL.

Any proposal is interesting :wink:

**Comment by miniche** [comment]
I think Apache 2.0 can be a good solution, at least for the beginning. It's more permissive than the GPL license, but less permissive than BSD. This seems to be a good compromise between freedom and respect of our work.

(Wikipedia : http://fr.wikipedia.org/wiki/Licence_Apache)

Eventually, CentralReport license may be modified during alpha versions or before the final version.

**Comment by Guimove** [comment]
For me Apache is a good solution for the moment. 
The only negative point is the autorisation of commercial usage of us sources, but I'm OK with the rest.

**Comment by Ninir** [comment]
For now it fits our needs. We'll see later if we need to change it. Mergeable.

**Comment by miniche** [comment]
Ok, the first alpha version will be released under Apache 2.0 version. Please see commit ea5b140 for "LICENSE" and "AUTHORS" files.
