### ISSUE TITLE
Refactor main scripts and security

### ISSUE THREAD

**Issue by miniche** [CentralReport/CentralReport#36]
For the moment, we have three main scripts in the CentralReport app:
- centralreport.py
- config.py
- test.py

These scripts contains a shebang, and can be executed with a simple ./centralreport.py (only if the user have the right to execute it).
Main advantage: the process will be identified as "centralreport" instead of "Python".

Some ideas:
- Can be added to the PATH?
- Extensions can be removed?
- Execution authorization can be added during installation?
- Can we call ./centralreport in init.d scripts?

**Comment by Ninir** [comment]
I don't really understand the 3 last questions. Could you add more details please?

**Comment by Guimove** [comment]
Yes we can remove the extension.
Moreover, as we manage the "start" and "stop", we can easily call it in init.d

**Comment by miniche** [comment]
Maybe we can add a specific "CentralReport User" to improve our security. This user has only few rights to execute CentralReport and use required os commands.

**Comment by Ninir** [comment]
@miniche :+1:

**Comment by Guimove** [comment]
Same

**Comment by miniche** [comment]
Done with the Pull Request https://github.com/CentralReport/CentralReport/pull/44
