### ISSUE TITLE
PEP 8: naming conventions

### ISSUE THREAD

**Issue by miniche** [CentralReport/CentralReport#37]
I think we must follow the python naming conventions, described in the PEP 8 (http://www.python.org/dev/peps/pep-0008/#naming-conventions).

Package and modules: lowercase with underscores
Classes: CapWords
Exception: CapWords, with "Error" suffix
Functions: lowercase with underscores, the first word must be a verb
Methods: same as functions
Variables: lowercase with underscores, the first word should not be a verb
Constants: CAPITAL_LETTERS, with underscores

We also need to respect the syntax convention (underscore before private methods, etc.).
A big refactor seems to be inevitable.

**Comment by Ninir** [comment]
Seems legit.

I'm not that comfortable with underscores but... if PEP says it so, let's go for it :D

**Comment by Guimove** [comment]
We should refactor now before getting a lot of code and dependancies.

**Comment by miniche** [comment]
@Ninir: Yeah. We usually use camelCase in other languages (like Java) or CapWords (C#). All major python projects (Django, CherryPy, Jinja, etc.) follow the PEP for the naming convention. I think it's better to fit our programmation habits to the standard of each language :)

**Comment by miniche** [comment]
@Guimove: You're right. I think we must do this before adding webservices support, no?

**Comment by Ninir** [comment]
For sure. It is a big refactor, but a quick one.
So... Will we follow all the PEP recommandations?

**Comment by miniche** [comment]
Well... No. Some PEP recommendations have been written a long time ago, such as the 80 line length limit.

We will update the Github wiki to specify rules that we must follow, and we will add some custom rules, those that seem to correspond better to CR philosophy.

**Comment by miniche** [comment]
A wiki page has been created: https://github.com/CentralReport/CentralReport/wiki/Naming-convention
