### ISSUE TITLE
Add a "History.md" file

### ISSUE THREAD

**Issue by Ninir** [CentralReport/CentralReport#46]
The goal of this file is to keep a complete history of what has been changed in the application.
### Reasons

As we want our project to be flexible, we **have** to provide changes, what has been broken (Backward Compatibility), what has been refactored. It is partially done with the [Added Changelog](https://github.com/miniche/CentralReport/pull/40).
Thus, developers forking the project will be able to fix more easily their plugins and/or our core project.
We should also provide the link to commits and/or Pull Requests in order to have the detailed code.
### Requirements
- [ ] Rebase commits in order to have something more clean.
- [ ] Add a sentence in the CHANGELOG file explaining that a more detailed list of what had changed is available for developers.
- [ ] Add a complete history/version with links to commits/PullRequest
- [ ] Do a script getting each commit per Pull Request? **[OPTIONNAL]**

**Comment by miniche** [comment]
Yeah, this will be very useful and mandatory. 

Just to have something to say (:stuck_out_tongue_winking_eye:), I think that the "change log" file must be more detailed than the "history".
We can keep a small history between version, and have a full change log between version and commits.

Or, according to Wikipedia (http://en.wikipedia.org/wiki/Changelog), we can also rename the actual "CHANGES" file to "NEWS" (or something else) and create this new file as changelog, changes, or history, whatever you want.

**Comment by Ninir** [comment]
Seems legit :)

**Comment by miniche** [comment]
The Symfony Changelog is a good example, according to you?

**Comment by Guimove** [comment]
A bit complex but ok for me.
Maybe, it exist some tools that generate this file automatically ?

**Comment by Guimove** [comment]
I think, We can play with the git log command to generate de changelog.

This command for exemple will output something like de SF Changelog :  
With a partition for each version

```
git log YOUR_LAST_VERSION_TAG..HEAD --no-merges --format=%B
```

**Comment by miniche** [comment]
Basically, I agree with Ninir. When you use a library or when you contribute to a project, you expect that the project is well documented.
For example, in our case, we will have majors changes between the 0.1.0 and the 0.2.0 version. It may be very useful to have some documentation about what is new, but also what is broken and what replace old features, in the code.

The "News" file (my "old" changelog) is more for the end-user than the developer.
The "Ninir Changelog" (:stuck_out_tongue_winking_eye:) is more for contributors and developers. It will be even more useful when we will be ready to do some plugins.

I think the "dev changelog" must be accurate and detailed: explanations about new features, changes, in which commit, why, etc. But, it's a hard work with the 250+ commits...

**Comment by miniche** [comment]
Just to share this with you, the [Django Release Notes](https://docs.djangoproject.com/en/dev/releases/1.4/) seems to be a good documentation, no?

**Comment by Ninir** [comment]
> Basically, I agree with Ninir. When you use a library or when you contribute to a project, you expect that the project is well documented.

Great to hear :D

> For example, in our case, we will have majors changes between the 0.1.0 and the 0.2.0 version. It may be very useful to have some documentation about what is new, but also what is broken and what replace old features, in the code.
> The "News" file (my "old" changelog) is more for the end-user than the developer.
> The "Ninir Changelog" () is more for contributors and developers. It will be even more useful when we will be ready to do some plugins.
> I think the "dev changelog" must be accurate and detailed: explanations about new features, changes, in which commit, why, etc. But, it's a hard work with the 250+ commits...

That's why we should be very efficient and clear with our commits, being as accurate and synthetic as possible :)

> Just to share this with you, the Django Release Notes seems to be a good documentation, no?

Indeed :)

**Comment by miniche** [comment]
I'm thinking... Perhaps it would be better to update the "NEWS" file into a markdown file, no?
It could be easier to read it!

**Comment by miniche** [comment]
The NEWS file is now written in markdown (since #95).
This issue is not required anymore.
