### ISSUE TITLE
Rename the "CentralReport" repository?

### ISSUE THREAD

**Issue by miniche** [CentralReport/CentralReport#49]
Now, we have a unique, beautiful and awesome Github organization. Just that.

But now, we have also the unix/linux agent/application (choose right words :smile:) which have the name of the organization. In few weeks, we will have also the C# version of the agent.

What do you think about renaming the "CentralReport" repository to correspond better to its function?
It's sad but I don't have any good idea...

**Comment by Guimove** [comment]
I think CentralReport is the global name of the application.

We can use some name like that : 

```
CentralReport Core => Web App (@Ninir part)
CentralReport Agent =>  Python part installed on monitored servers
```

To differentiate the OS, we could simply use the name of the OS : 

```
CentralReport Agent Unix/Linux
CentralReport Agent Windows
```

Or something more kikoulolgodiflex like : 

```
WinReport Agent
DebReport Agent
```
