### ISSUE TITLE
Typo mistake on install.sh

### ISSUE THREAD

**Issue by Azaret** [CentralReport/CentralReport#51]
Hi,

Got a mistake on the install script on the dev branch.
The script said we can edit the cfg file on /etc/centralreport.cfg

"For more options, you can edit the config file at /etc/centralreport.cfg"

Which have been moved to /etc/centralreport/

Cheers.

**Comment by miniche** [comment]
Thanks for your report, @Azaret.
As you can see, I think it's fixed by one (or more ?) previous commit :)

**Comment by miniche** [comment]
Fixed with #51. Merged in the develop branch.
