### ISSUE TITLE
Rename URLs in the code

### ISSUE THREAD

**Issue by Ninir** [CentralReport/CentralReport#55]
Currently we still have written URLs in the code pointing to the previous `miniche/CentralReport` whereas it should be `CentralReport/CentralReport`.

**Comment by miniche** [comment]
A little poll.

What do you prefer?
- Links to the organization: `https://github.com/CentralReport`
- Links to the project: `https://github.com/CentralReport/CentralReport`

**Comment by Guimove** [comment]
I prefer the project

**Comment by Ninir** [comment]
Depends on the case IMO.
For edge cases: the organisation. For clear purposes: the projet :)

**Comment by miniche** [comment]
Fixed in Pull Request https://github.com/CentralReport/CentralReport/pull/60
