### ISSUE TITLE
Serializer Component

### ISSUE THREAD

**Issue by Ninir** [CentralReport/CentralReport#56]
In order to reduce code redundancies when serializing data, we should implement a serializer component, which will be in charge to take a data, serializes it in a given format, and returns the serialized object.

IMO, it is way better to do such think in order to get rid of all the serialize/json_serialize methods we could have in each classes. Something like:

``` python
class Serializer():

    def serialize(self, content, format=None):
        """
            Serializes data in a given format.
        """

        # Do some stuff...

        # original_object = content
        # serialized_data = json_dumps(original_object)

        return serialized_data

    def deserialize(self, content, format=None):
        """
            Deserializes a serialized content back to its original type.
        """

        # Do some stuff...

        # serialized_data = content
        # original_object = dict()
        # from StringIO import StringIO
        # io = StringIO('["streaming API"]')
        # original_object = json.load(io)

        return original_object
```

This is an example and should not be taken as is. We could also use reflection which will allow more benefits from it.

**Comment by miniche** [comment]
Very good idea!
It's a work for super @Guimove! :+1:
