### ISSUE TITLE
RAM mal calculée

### ISSUE THREAD

**Issue by Xefir** [CentralReport/CentralReport#64]
Sur une Debian (mais je pense que cela le fait aussi sur les autres systèmes), la RAM affichée dans CentralReport est la mémoire allouée et non la mémoire effectivement utilisée.

Pourquoi ne pas faire comme htop et afficher une barre générale découpée en plusieurs morceaux montrant la mémoire allouée, la mémoire système et la mémoire inactive ?

Voir ici un exemple et les détails : https://twitter.com/xefir_destiny/status/321241197861543937

**Comment by miniche** [comment]
En effet, la partie web affiche toute la mémoire vive allouée, et non seulement celle active.
Dans le collecteur de données, on fait bien la différence entre la RAM active et inactive, mais les deux valeurs sont regroupées en une seule sur la partie web.

On va faire une grosse refonte de ce serveur web integré prochainement, afin de le rendre beaucoup plus verbeux (et revoir totalement son design aussi) : on a beaucoup d'informations que nous n'affichons pas (le CPU user vs CPU système, RAM active vs inactive vs réservée, des informations systèmes, etc.).

Stay tuned :)

**Comment by miniche** [comment]
Ouch... 10 mois se sont déjà écoulés ! On va mettre en place le tout nouveau design avec beaucoup plus de possibilités. L'affichage détaillée de la RAM en fera parti bien entendu :)

https://twitter.com/miniCharles/status/426501438840532992

ETA février.

**Comment by miniche** [comment]
Available in the latest release :)
